package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/wambozi/aether/internal/config"
)

// runInit implements the "aetherd init" subcommand.
// It bootstraps everything a new user needs: shell hook, config file,
// data directory, and (on Linux) the systemd user service.
func runInit() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot determine home directory: %w", err)
	}

	fmt.Println("aetherd init: bootstrapping Aether OS daemon")
	fmt.Println()

	// 1. Shell hook
	if err := installShellHook(home); err != nil {
		fmt.Fprintf(os.Stderr, "  [warn] shell hook: %v\n", err)
	}

	// 2. Config file
	if err := installConfig(); err != nil {
		fmt.Fprintf(os.Stderr, "  [warn] config: %v\n", err)
	}

	// 3. Data directory
	if err := installDataDir(home); err != nil {
		fmt.Fprintf(os.Stderr, "  [warn] data dir: %v\n", err)
	}

	// 4. Systemd service (Linux only)
	if runtime.GOOS == "linux" {
		if err := installSystemdService(home); err != nil {
			fmt.Fprintf(os.Stderr, "  [warn] systemd: %v\n", err)
		}
	}

	fmt.Println()
	fmt.Println("aetherd init: done. Start a new shell or source your rc file to activate the hook.")
	return nil
}

// installShellHook appends the appropriate source line to ~/.zshrc or ~/.bashrc.
func installShellHook(home string) error {
	shell := os.Getenv("SHELL")

	var rcFile, hookFile, sourceLine string
	switch {
	case strings.Contains(shell, "zsh"):
		rcFile = filepath.Join(home, ".zshrc")
		hookFile = "shell-hook.zsh"
		sourceLine = `source "$HOME/.config/aether/shell-hook.zsh"`
	case strings.Contains(shell, "bash"):
		rcFile = filepath.Join(home, ".bashrc")
		hookFile = "shell-hook.bash"
		sourceLine = `source "$HOME/.config/aether/shell-hook.bash"`
	default:
		fmt.Println("  [skip] shell hook: unrecognised SHELL, install manually")
		return nil
	}

	// Copy hook file to config dir.
	hookSrc := filepath.Join(home, ".config", "aether", hookFile)
	if err := copyEmbeddedHook(hookFile, hookSrc); err != nil {
		return fmt.Errorf("copy hook: %w", err)
	}

	// Check if already present in rc file.
	rc, err := os.ReadFile(rcFile)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("read %s: %w", rcFile, err)
	}
	if strings.Contains(string(rc), sourceLine) {
		fmt.Printf("  [ok]   shell hook already in %s\n", rcFile)
		return nil
	}

	// Append source line.
	f, err := os.OpenFile(rcFile, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return fmt.Errorf("open %s: %w", rcFile, err)
	}
	defer f.Close()

	_, err = fmt.Fprintf(f, "\n# Aether OS shell hook\n%s\n", sourceLine)
	if err != nil {
		return err
	}
	fmt.Printf("  [ok]   shell hook appended to %s\n", rcFile)
	return nil
}

// copyEmbeddedHook copies a hook from the installed scripts location to dst.
// It tries the executable directory first, then falls back to the repo root.
func copyEmbeddedHook(name, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o700); err != nil {
		return err
	}

	// Try to locate the hook relative to the running binary.
	exe, _ := os.Executable()
	candidates := []string{
		filepath.Join(filepath.Dir(exe), "..", "scripts", name),
		filepath.Join("/usr/local/share/aether/scripts", name),
		filepath.Join(filepath.Dir(exe), "..", "..", "scripts", name),
	}

	for _, src := range candidates {
		data, err := os.ReadFile(src)
		if err != nil {
			continue
		}
		return os.WriteFile(dst, data, 0o644)
	}
	// Hook file not found — not fatal, just skip.
	fmt.Printf("  [skip] %s not found (install manually to %s)\n", name, dst)
	return nil
}

// installConfig creates ~/.config/aether/config.toml from defaults if absent.
func installConfig() error {
	cfgPath := config.DefaultPath()
	if _, err := os.Stat(cfgPath); err == nil {
		fmt.Printf("  [ok]   config already exists at %s\n", cfgPath)
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(cfgPath), 0o700); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(cfgPath), err)
	}

	// Write a minimal default config.
	const defaultTOML = `# Aether daemon configuration
# Generated by aetherd init

[daemon]
log_level = "info"

[notifier]
level = 2
digest_time = "09:00"

[cactus]
url = "http://127.0.0.1:8080"
routing_mode = "localfirst"
timeout_seconds = 60

[retention]
raw_event_days = 90
`
	if err := os.WriteFile(cfgPath, []byte(defaultTOML), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", cfgPath, err)
	}
	fmt.Printf("  [ok]   config written to %s\n", cfgPath)
	return nil
}

// installDataDir creates the aetherd data directory.
func installDataDir(home string) error {
	base := os.Getenv("XDG_DATA_HOME")
	if base == "" {
		base = filepath.Join(home, ".local", "share")
	}
	dir := filepath.Join(base, "aetherd")

	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	fmt.Printf("  [ok]   data directory: %s\n", dir)
	return nil
}

// installSystemdService copies the unit file and enables the service.
func installSystemdService(home string) error {
	unitDir := filepath.Join(home, ".config", "systemd", "user")
	if err := os.MkdirAll(unitDir, 0o700); err != nil {
		return fmt.Errorf("mkdir systemd user dir: %w", err)
	}
	dst := filepath.Join(unitDir, "aetherd.service")

	// Locate the bundled service file.
	exe, _ := os.Executable()
	candidates := []string{
		filepath.Join(filepath.Dir(exe), "..", "deploy", "aetherd.service"),
		filepath.Join(filepath.Dir(exe), "..", "..", "deploy", "aetherd.service"),
		"/usr/local/share/aether/aetherd.service",
	}
	var src string
	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			src = c
			break
		}
	}
	if src == "" {
		fmt.Println("  [skip] aetherd.service not found — copy deploy/aetherd.service manually")
		return nil
	}

	data, err := os.ReadFile(src)
	if err != nil {
		return fmt.Errorf("read service file: %w", err)
	}
	if err := os.WriteFile(dst, data, 0o644); err != nil {
		return fmt.Errorf("write service file: %w", err)
	}
	fmt.Printf("  [ok]   service file written to %s\n", dst)

	// Enable and start the service.
	cmds := [][]string{
		{"systemctl", "--user", "daemon-reload"},
		{"systemctl", "--user", "enable", "--now", "aetherd"},
	}
	for _, args := range cmds {
		out, err := exec.Command(args[0], args[1:]...).CombinedOutput()
		if err != nil {
			fmt.Printf("  [warn] %s: %v — %s\n", strings.Join(args, " "), err, strings.TrimSpace(string(out)))
		} else {
			fmt.Printf("  [ok]   %s\n", strings.Join(args, " "))
		}
	}
	return nil
}
