// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDenier is an autogenerated mock type for the Denier type
type MockDenier struct {
	mock.Mock
}

// Deny provides a mock function with given fields: ctx, rule, action, reason
func (_m *MockDenier) Deny(ctx context.Context, rule string, action string, reason string) error {
	ret := _m.Called(ctx, rule, action, reason)

	if len(ret) == 0 {
		panic("no return value specified for Deny")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, rule, action, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockDenier creates a new instance of MockDenier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDenier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDenier {
	mock := &MockDenier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
