package vm

import (
	"context"
	"time"
)

// NOTE: This file imports ONLY stdlib + context + time. It does NOT import
// launcherprofile. StartSpec fields are primitives; the merge from
// LauncherProfile into StartSpec happens at cmd/sigild/main.go before
// Driver.Start is invoked. This keeps the Driver interface independent of the
// launcher-profile schema and prevents interface shape changes when
// LauncherProfile gains a field.

// SessionID is the opaque identifier sigild assigns to a VM session.
// UUID-shaped in practice (see sessions.id column). Passed across the Driver
// interface and all socket methods.
type SessionID string

// StartSpec is the merged input to VM provisioning. It is assembled by
// cmd/sigild/main.go from the socket VMStart request payload (from Kenaz),
// launcherprofile.Read() (from disk), and sigild-generated values.
// vmdriver implementations receive the fully merged spec; they never call
// launcherprofile.Read() themselves.
type StartSpec struct {
	// From StartVMProfile (Kenaz socket request payload):
	Name       string   // ≤64 UTF-8 chars, user-supplied
	PolicyID   string   // one of the configured policy IDs
	Apps       []string // subset of workbench-app keys
	EgressTier string   // one of: allowlist | restricted | vault-only | none

	// From LauncherProfile (sigild reads the JSON, merges here as primitives):
	ImagePath       string   // absolute path to sigil-os QCOW2/VHDX
	Editor          string   // "cursor" | "vscode" | "zed" | ...
	Shell           string   // "zsh" | "bash" | ...
	ContainerEngine string   // "docker" | "podman" | ""
	WorkbenchApps   []string // launcher-configured app list
	MemoryMB        uint64   // 0 = platform default
	CPUCount        uint8    // 0 = platform default

	// Generated by sigild at VMStart time:
	OverlayPath string // absolute path to the ephemeral overlay file
	VsockCID    uint32 // 3..2^32-2 on Linux; 0 on macOS (VZ assigns internally)
}

// Snapshot is the answer to "what state is this VM in right now?"
// It is returned by Driver.Status and is not used for hot-path stat updates
// (Driver.Subscribe handles those).
type Snapshot struct {
	State     LifecycleState
	StartedAt time.Time // UTC; zero-valued if unknown
	EndedAt   time.Time // UTC; zero-valued if non-terminal
	VsockCID  uint32    // 0 on macOS
	PID       int       // hypervisor process ID; 0 if terminal
}

// StatSnapshot is pushed on the channel returned by Driver.Subscribe at
// whatever cadence the driver can produce. Consumers decouple their update
// rate from this push rate.
type StatSnapshot struct {
	Timestamp         time.Time
	CPUPercent        float64 // 0..100 * CPUCount (can exceed 100 on multi-core)
	CPUCores          uint8
	MemoryUsedMB      uint64
	MemoryAllocatedMB uint64
}

// Driver abstracts the hypervisor backend. It is a consumer-defined interface;
// production implementations live in sigil/internal/vmdriver/ (build-tagged
// per platform). The fake implementation (vmdriver.NewFake) is used in tests.
//
// All methods accept a context.Context as their first argument. Callers must
// respect cancellation. Implementations must not retain the context beyond the
// lifetime of the call (except Subscribe, which ties the channel lifetime to ctx).
type Driver interface {
	// Start provisions and boots a new VM from spec. It returns the SessionID
	// assigned by the driver. The caller is responsible for persisting the
	// session record; the driver's sole concern is the hypervisor process.
	Start(ctx context.Context, spec StartSpec) (SessionID, error)

	// Stop initiates a graceful shutdown of the VM identified by id.
	// Implementations must not block indefinitely; they should apply an
	// internal timeout and fall back to a forceful termination.
	Stop(ctx context.Context, id SessionID) error

	// Status returns a point-in-time Snapshot of the VM's lifecycle state.
	Status(ctx context.Context, id SessionID) (Snapshot, error)

	// Subscribe returns a read-only channel that receives StatSnapshot values
	// at the driver's native cadence. The channel is closed when the VM exits
	// or when ctx is cancelled. Callers must drain the channel or risk blocking
	// the driver's send path; a non-blocking select with a default is idiomatic.
	Subscribe(ctx context.Context, id SessionID) (<-chan StatSnapshot, error)

	// Health performs a lightweight liveness check against the hypervisor
	// (e.g. a QMP ping or a JSON-line no-op). Returns nil if the VM is
	// reachable, or an error describing the failure mode.
	Health(ctx context.Context, id SessionID) error

	// Close releases all resources held by the driver (tracked processes, open
	// sockets, CID allocations). It is called once, on daemon shutdown.
	// Implementations must terminate all running VMs before returning.
	Close() error
}

// SessionSampler is the consumer-defined interface through which vm.Manager
// communicates live stat data to the vmstats package. vm declares the
// interface; vmstats.Sampler satisfies it. cmd/sigild/main.go wires the
// concrete implementation.
//
// The zero value of any struct field of type SessionSampler is nil; callers
// must nil-check before invoking methods (Manager handles nil gracefully).
type SessionSampler interface {
	// AttachSession starts consuming stat snapshots from ch and caching them
	// under id. The goroutine exits when ch is closed or ctx is cancelled.
	AttachSession(ctx context.Context, id SessionID, ch <-chan StatSnapshot)

	// DetachSession stops consuming and drops the cached snapshot for id.
	// It is safe to call when no session is attached.
	DetachSession(id SessionID)

	// Read returns the most-recent StatSnapshot for id, and true if one exists.
	// Returns (StatSnapshot{}, false) if the session has no cached data.
	Read(id SessionID) (StatSnapshot, bool)
}
