// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLedgerEmitter is an autogenerated mock type for the LedgerEmitter type
type MockLedgerEmitter struct {
	mock.Mock
}

// EmitVMSpawn provides a mock function with given fields: ctx, sessionID, payload
func (_m *MockLedgerEmitter) EmitVMSpawn(ctx context.Context, sessionID string, payload interface{}) error {
	ret := _m.Called(ctx, sessionID, payload)

	if len(ret) == 0 {
		panic("no return value specified for EmitVMSpawn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, sessionID, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitVMTeardown provides a mock function with given fields: ctx, sessionID, payload
func (_m *MockLedgerEmitter) EmitVMTeardown(ctx context.Context, sessionID string, payload interface{}) error {
	ret := _m.Called(ctx, sessionID, payload)

	if len(ret) == 0 {
		panic("no return value specified for EmitVMTeardown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, sessionID, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockLedgerEmitter creates a new instance of MockLedgerEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLedgerEmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLedgerEmitter {
	mock := &MockLedgerEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
