// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	vm "github.com/sigil-tech/sigil/internal/vm"
	mock "github.com/stretchr/testify/mock"
)

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *MockDriver) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Health provides a mock function with given fields: ctx, id
func (_m *MockDriver) Health(ctx context.Context, id vm.SessionID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, vm.SessionID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields: ctx, spec
func (_m *MockDriver) Start(ctx context.Context, spec vm.StartSpec) (vm.SessionID, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 vm.SessionID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vm.StartSpec) (vm.SessionID, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vm.StartSpec) vm.SessionID); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Get(0).(vm.SessionID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, vm.StartSpec) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Status provides a mock function with given fields: ctx, id
func (_m *MockDriver) Status(ctx context.Context, id vm.SessionID) (vm.Snapshot, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 vm.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vm.SessionID) (vm.Snapshot, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vm.SessionID) vm.Snapshot); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(vm.Snapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, vm.SessionID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Stop provides a mock function with given fields: ctx, id
func (_m *MockDriver) Stop(ctx context.Context, id vm.SessionID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, vm.SessionID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: ctx, id
func (_m *MockDriver) Subscribe(ctx context.Context, id vm.SessionID) (<-chan vm.StatSnapshot, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan vm.StatSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vm.SessionID) (<-chan vm.StatSnapshot, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vm.SessionID) <-chan vm.StatSnapshot); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan vm.StatSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, vm.SessionID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
