// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	vm "github.com/sigil-tech/sigil/internal/vm"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionSampler is an autogenerated mock type for the SessionSampler type
type MockSessionSampler struct {
	mock.Mock
}

// AttachSession provides a mock function with given fields: ctx, id, ch
func (_m *MockSessionSampler) AttachSession(ctx context.Context, id vm.SessionID, ch <-chan vm.StatSnapshot) {
	_m.Called(ctx, id, ch)
}

// DetachSession provides a mock function with given fields: id
func (_m *MockSessionSampler) DetachSession(id vm.SessionID) {
	_m.Called(id)
}

// Read provides a mock function with given fields: id
func (_m *MockSessionSampler) Read(id vm.SessionID) (vm.StatSnapshot, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 vm.StatSnapshot
	var r1 bool
	if rf, ok := ret.Get(0).(func(vm.SessionID) (vm.StatSnapshot, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(vm.SessionID) vm.StatSnapshot); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(vm.StatSnapshot)
	}

	if rf, ok := ret.Get(1).(func(vm.SessionID) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// NewMockSessionSampler creates a new instance of MockSessionSampler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionSampler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionSampler {
	mock := &MockSessionSampler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
